
name: Build PluginBuilder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Create venv
        shell: cmd
        run: |
          python -m venv .venv_build
          call .venv_build\Scripts\activate.bat
          python -m pip install --upgrade pip

      - name: Install Requirements
        shell: cmd
        run: |
          call .venv_build\Scripts\activate.bat
          pip install nuitka pyside6

      - name: Install Dependency Walker
        uses: onesoftqwq/dependency-walker-installer@v1.0

      - name: Build EXE
        shell: cmd
        run: |
          call .venv_build\Scripts\activate.bat

          python -m nuitka ^
            --standalone ^
            --onefile ^
            --enable-plugin=pyside6 ^
            --windows-console-mode=disable ^
            --output-filename=PluginBuilder.exe ^
            PluginBuilder.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PluginBuilder
          path: PluginBuilder.exe
